### ISSUE TITLE
RUST error in Conda stable version

### ISSUE THREAD

**Issue by TanXinjiang** [GeneDx/pgr-tk#21]
Hello, 
Thanks for the excellent toolkit and congratulations for the publication. I have installed pgr-tk v0.3.6 as introduced in README.md, and tried to create pgr minimizer database with HPRC-yr1.agc with:
`pgr-mdb HPRC-yr1.agc HPRC-yr1`
but it raised an error as :
`thread 'main' panicked at 'called 'Result::unwrap()' on an 'Err' value: Error { kind: InvalidData, message: "stream did not contain valid UTF-8" src/bin/pgr-mdb.rs:47:25  
note: run with 'RUST_BACKTRACE=1' environment variable to display a backtrace`
Same error when trying to pip install as #1 
Thanks!
Xinjiang Tan

**Comment by cschin** [comment]
@TanXinjiang thank.  you should create a file containing the path to the "HPRC-yr1.agc" as the first argument of the `pgr-mdb` command. It don't take the "HPRC-yr1.agc" as input directly.

**Comment by cschin** [comment]
@TanXinjiang, I just have to do this, this is an example:

```
agc create human_GRCh38_no_alt_analysis_set.fasta -i file_list -o test.agc
echo test.agc > input
pgr-mdbinput test
pgr-fetch-seqs  test --list
```
the `file_list` contains the pangenome assemblies that I am interested in using

**Comment by TanXinjiang** [comment]
@cschin Thanks a lot! I've managed to create the index from command line, but the other functions seem to only work in the python environment ? (I only found pgr-mdb under ~/anaconda3/envs/pgr-tk/bin/)
