### ISSUE TITLE
`pgr-mdb` is the only available command after conda install

### ISSUE THREAD

**Issue by aryarm** [GeneDx/pgr-tk#25]
Hi! Thanks for making PGR-TK. We're very interested in working with your toolkit! And it seems like a great resource for the community.

---

I tried to install PGR-TK using conda but was only able to run the `pgr-mdb` command. My understanding based on [the README](https://github.com/GeneDx/pgr-tk/blob/3fc189e839cb8994eb001d2f9e956a3ed4fd767a/README.md#documentation-usage-and-examples) is that there are many other `pgr` commands.

Is there a reason your conda recipe copies only the `pgr-mdb` command into the user's bin, @cschin?

https://github.com/bioconda/bioconda-recipes/blob/15662093a41a5ca09a66355b179e4290e82c2026/recipes/pgr-tk/build.sh#L41

**Comment by cschin** [comment]
@aryarm  I think that is just how the bioconda build is... if you are comfortable with the Rust's Cargo environment ( you need to install rust compiler and Cargo), that is a better way with the rust code in my opinion.

**Comment by aryarm** [comment]
hmm, I guess I'm curious about why the recipe doesn't have something like this, instead?

```diff
-cp $SRC_DIR/target/release/pgr-mdb $PREFIX/bin
+cp $SRC_DIR/target/release/pgr-* $PREFIX/bin
```

That way, all of the pgr commands would be available to the user, right?

**Comment by cschin** [comment]
I see. The initial version of PGR-TK has limit command line. The pgr-mdb was necessary for using with the python library. Yes, the script should install additional supported command line tools. You can download the pre-built binaries from the release page this this GitHub site as well.

**Comment by aryarm** [comment]
great, thanks! we'll use the binaries if we need the CLI in the meantime
